### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Madji** [mrgigabyte/proxybot#1]
Tell me there is no possibility to translate this function on the tg-cli. Not to use telegram Api bot. People neat to write using bot.. I Have another account telegram of such a functionality is not enough to use a phone and 2 accounts at once

**Comment by mrgigabyte** [comment]
I'm not exactly sure as to what do you mean by 'translating'. But yeah, you cannot simply use this code for tg-cli bots. You would have to write an entirely different code for that.
